package cmd

import (
	"agent-sentry/internal/database"
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

var reportID int

var reportCmd = &cobra.Command{
	Use:   "report",
	Short: "Generate a Markdown incident report",
	Long: `Generates a beautiful Markdown report for a specific incident.
Example:
  agent-sentry report --id 3`,
	Run: func(cmd *cobra.Command, args []string) {
		generateReport(reportID)
	},
}

func init() {
	rootCmd.AddCommand(reportCmd)
	reportCmd.Flags().IntVar(&reportID, "id", 0, "Incident ID to generate report for (required)")
	reportCmd.MarkFlagRequired("id")
}

func generateReport(id int) {
	if err := database.InitDB(); err != nil {
		fmt.Printf("Error: Failed to connect to database: %v\n", err)
		os.Exit(1)
	}
	defer database.CloseDB()

	inc, err := database.GetIncidentByID(id)
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		os.Exit(1)
	}

	// Build the Markdown report
	var sb strings.Builder

	// Header
	sb.WriteString("# 🛡️ Agent-Sentry — Incident Report\n\n")
	sb.WriteString("---\n\n")

	// Status Badge
	statusEmoji := "✅"
	statusLabel := "Success"
	switch inc.ExitReason {
	case "LOOP_DETECTED":
		statusEmoji = "🚨"
		statusLabel = "Loop Detected & Killed"
	case "WATCHDOG_ALERT":
		statusEmoji = "🔍"
		statusLabel = "Watchdog Alert (No Kill)"
	case "COMMAND_FAILURE":
		statusEmoji = "❌"
		statusLabel = "Command Failure"
	case "USER_TERMINATED":
		statusEmoji = "⏹️"
		statusLabel = "User Terminated"
	}

	sb.WriteString("| Field | Value |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString(fmt.Sprintf("| **Incident ID** | `#%d` |\n", inc.ID))
	sb.WriteString(fmt.Sprintf("| **Timestamp** | %s |\n", inc.Timestamp))
	sb.WriteString(fmt.Sprintf("| **Status** | %s %s |\n", statusEmoji, statusLabel))
	sb.WriteString(fmt.Sprintf("| **Model** | `%s` |\n", inc.ModelName))
	sb.WriteString(fmt.Sprintf("| **Max CPU** | `%.1f%%` |\n", inc.MaxCPU))
	sb.WriteString("\n")

	// Kill Event Summary
	sb.WriteString("## ⚡ Event Summary\n\n")
	sb.WriteString(fmt.Sprintf("**Command Executed:**\n```bash\n%s\n```\n\n", inc.Command))
	sb.WriteString(fmt.Sprintf("**Exit Reason:** %s %s\n\n", statusEmoji, statusLabel))
	sb.WriteString(fmt.Sprintf("**Peak CPU Usage:** `%.1f%%`\n\n", inc.MaxCPU))

	// Loop Pattern Section (only if pattern is meaningful)
	if inc.Pattern != "" && inc.Pattern != "N/A" {
		sb.WriteString("## 🔁 Detected Loop Pattern\n\n")
		sb.WriteString("The Sentry's fuzzy detection engine identified the following **normalized stagnation pattern** repeating across the process's output:\n\n")
		sb.WriteString(fmt.Sprintf("```\n%s\n```\n\n", inc.Pattern))
		sb.WriteString("> This pattern was matched using Levenshtein similarity at a **≥90%** threshold after normalizing timestamps, hex addresses, and numeric values.\n\n")
	}

	// ROI / Money Saved Section
	sb.WriteString("## 💰 ROI — Estimated Savings\n\n")

	rate := 0.03
	if inc.ModelName == "gpt-3.5-turbo" {
		rate = 0.002
	}

	sb.WriteString("| Metric | Value |\n")
	sb.WriteString("|---|---|\n")
	sb.WriteString(fmt.Sprintf("| **Model** | `%s` |\n", inc.ModelName))
	sb.WriteString(fmt.Sprintf("| **Rate** | $%.3f/min |\n", rate))
	sb.WriteString(fmt.Sprintf("| **Estimated Savings** | **$%.4f** |\n", inc.TokenSavingsEstimate))

	if inc.ExitReason == "LOOP_DETECTED" || inc.ExitReason == "WATCHDOG_ALERT" {
		sb.WriteString(fmt.Sprintf("\n> 🛡️ By catching this loop, Agent-Sentry prevented an estimated **$%.2f** in wasted API tokens.\n\n", inc.TokenSavingsEstimate))
	}
	sb.WriteString("\n")

	// Footer
	sb.WriteString("---\n\n")
	sb.WriteString(fmt.Sprintf("*Generated by [Agent-Sentry](https://github.com/agent-sentry) on %s*\n", time.Now().Format("2006-01-02 15:04:05")))

	// Write to file
	filename := fmt.Sprintf("sentry_report_%d.md", id)
	if err := os.WriteFile(filename, []byte(sb.String()), 0644); err != nil {
		fmt.Printf("Error writing report: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("✅ Report generated: %s\n", filename)
}
