package feedback

import (
	"fmt"
	"os"
	"strings"
	"time"
)

const FeedbackFile = "agent_feedback.txt"

// FeedbackData holds the information needed to generate feedback.
type FeedbackData struct {
	Command    string
	Pattern    string
	ExitReason string
	MaxCPU     float64
	ModelName  string
	Savings    float64
}

// GenerateFeedback creates an agent_feedback.txt file containing
// a Markdown-formatted summary of what went wrong and actionable guidance.
func GenerateFeedback(data FeedbackData) error {
	var sb strings.Builder

	sb.WriteString("# 🛡️ Agent-Sentry Feedback\n\n")
	sb.WriteString("---\n\n")
	sb.WriteString("## ⚠️ Loop Detected in Your Process\n\n")
	sb.WriteString("Agent-Sentry detected that your process entered a **repetitive loop** and intervened.\n\n")

	sb.WriteString("### What Happened\n\n")
	sb.WriteString(fmt.Sprintf("- **Command:** `%s`\n", data.Command))
	sb.WriteString(fmt.Sprintf("- **Exit Reason:** %s\n", data.ExitReason))
	sb.WriteString(fmt.Sprintf("- **Peak CPU:** %.1f%%\n", data.MaxCPU))
	sb.WriteString(fmt.Sprintf("- **Model:** %s\n", data.ModelName))
	sb.WriteString(fmt.Sprintf("- **Est. Savings:** $%.4f\n\n", data.Savings))

	sb.WriteString("### The Repeating Pattern\n\n")
	sb.WriteString("Your process's output contained this normalized repeating pattern:\n\n")
	sb.WriteString(fmt.Sprintf("```\n%s\n```\n\n", data.Pattern))

	sb.WriteString("### Suggestion for Next Run\n\n")
	sb.WriteString("1. **Check for infinite loops** — Review any `while True` or recursive calls in your code.\n")
	sb.WriteString("2. **Add exit conditions** — Ensure your loops have proper termination criteria.\n")
	sb.WriteString("3. **Rate-limit API calls** — If calling external APIs in a loop, add delays.\n")
	sb.WriteString("4. **Check for stale state** — Ensure variables are being updated within the loop body.\n\n")

	sb.WriteString("### For AI Agents\n\n")
	sb.WriteString("If you are an AI agent reading this feedback:\n")
	sb.WriteString("- **DO NOT** repeat the same action that caused this loop.\n")
	sb.WriteString("- **MODIFY** your approach before retrying.\n")
	sb.WriteString("- Consider the pattern above as a **blacklisted behavior**.\n\n")

	sb.WriteString("---\n\n")
	sb.WriteString(fmt.Sprintf("*Generated by Agent-Sentry on %s*\n", time.Now().Format("2006-01-02 15:04:05")))

	if err := os.WriteFile(FeedbackFile, []byte(sb.String()), 0644); err != nil {
		return fmt.Errorf("failed to write feedback: %v", err)
	}

	fmt.Printf("[Sentry] 📝 Feedback file generated: %s\n", FeedbackFile)
	return nil
}

// ReadFeedback reads the feedback file and returns its content.
func ReadFeedback(path string) (string, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return "", fmt.Errorf("failed to read feedback file: %v", err)
	}
	return string(data), nil
}

// CleanupFeedback removes the feedback file after injection.
func CleanupFeedback(path string) {
	os.Remove(path)
	fmt.Printf("[Sentry] 🗑️  Feedback file cleaned up: %s\n", path)
}
